---
apiVersion: v1
kind: Namespace
metadata:
    name: ernest-ns
    labels: 
        app: fortune
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: fortune-deploy
    namespace: ernest-ns
    labels:
        app: fortune
spec:
    replicas: 2
    selector:
        matchLabels:
            app: fortune-pod
    template:
        metadata:
            name: fortune-pod
            labels:
                app: fortune-pod
        spec:
            containers:
            - name: fortune-container
              image: chukmunnlee/fortune:v1
              imagePullPolicy: IfNotPresent
              ports:
              - name: http-port
                containerPort: 3000
